[project]
name = "smart-counter"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "onnx>=1.19.1",
    "pandas>=2.3.3",
    "streamlit>=1.52.0",
    "ultralytics>=8.3.233",
]
